### ISSUE TITLE
Upgrade to angular 4

### ISSUE THREAD

**Issue by zack9433** [mgechev/ngresizable#8]
I try to upgrade dependencies to angular@4.0.2 and build demo using `build-demo` script but hosting demo folder by local web server and run into a problem.

```
Unhandled Promise rejection: Cannot read property 'call' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'call' of undefined
    at new ApplicationRef_ (core.umd.js:4973)
    at DemoModuleInjector.createInternal (module.ngfactory.js:114)
    at DemoModuleInjector.NgModuleInjector.create (core.umd.js:3544)
    at NgModuleFactory.create (core.umd.js:3517)
    at eval (core.umd.js:4755)
    at e.invoke (zone.min.js:1)
    at Object.onInvoke (core.umd.js:4132)
    at e.invoke (zone.min.js:1)
    at n.run (zone.min.js:1)
    at NgZone.run (core.umd.js:4001)
    at PlatformRef_._bootstrapModuleFactoryWithZone (core.umd.js:4753)
    at eval (core.umd.js:4794)
    at e.invoke (zone.min.js:1)
    at n.run (zone.min.js:1)
    at zone.min.js:1 TypeError: Cannot read property 'call' of undefined
    at new ApplicationRef_ (http://localhost:8080/vendor/core.umd.js:4973:99)
    at DemoModuleInjector.createInternal (ng:///DemoModule/module.ngfactory.js:114:29)
    at DemoModuleInjector.NgModuleInjector.create (http://localhost:8080/vendor/core.umd.js:3544:76)
    at NgModuleFactory.create (http://localhost:8080/vendor/core.umd.js:3517:18)
    at eval (http://localhost:8080/vendor/core.umd.js:4755:61)
    at e.invoke (http://localhost:8080/vendor/zone.min.js:1:19239)
    at Object.onInvoke (http://localhost:8080/vendor/core.umd.js:4132:37)
    at e.invoke (http://localhost:8080/vendor/zone.min.js:1:19179)
    at n.run (http://localhost:8080/vendor/zone.min.js:1:14963)
    at NgZone.run (http://localhost:8080/vendor/core.umd.js:4001:62)
    at PlatformRef_._bootstrapModuleFactoryWithZone (http://localhost:8080/vendor/core.umd.js:4753:23)
    at eval (http://localhost:8080/vendor/core.umd.js:4794:59)
    at e.invoke (http://localhost:8080/vendor/zone.min.js:1:19239)
    at n.run (http://localhost:8080/vendor/zone.min.js:1:14963)
    at http://localhost:8080/vendor/zone.min.js:1:12026
```

**Comment by mgechev** [comment]
I'll do that today.

**Comment by mgechev** [comment]
It's not an issue in ngresizable. You should be able to freely use it with Angular 4. The problem comes from some imports.

The fix for the demo should be published by the end of the day.

**Comment by mgechev** [comment]
https://github.com/mgechev/ngresizable/commit/a4cb6a9424ba2b33b26db8f7fb850cb8bb83a2c1
